lavapipe: Fix gnu-empty-initializer error in NV_cooperative_matrix2 conversions
Fixes the following building errors happening with clang:

FAILED: src/gallium/frontends/lavapipe/liblavapipe_st.a.p/nir_lvp_nir_lower_cooperative_matrix.c.o
...
../src/gallium/frontends/lavapipe/nir/lvp_nir_lower_cooperative_matrix.c:113:45: error: use of GNU empty initializer extension [-Werror,-Wgnu-empty-initializer]
   nir_def *comps[NIR_MAX_VEC_COMPONENTS] = {};
                                            ^
../src/gallium/frontends/lavapipe/nir/lvp_nir_lower_cooperative_matrix.c:114:49: error: use of GNU empty initializer extension [-Werror,-Wgnu-empty-initializer]
   nir_def *out_comps[NIR_MAX_VEC_COMPONENTS] = {};
                                                ^
2 errors generated.

Fixes: 5f3f091e ("lavapipe: add NV_cooperative_matrix2 conversions support")
Part-of: <https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/39652>