ci: Update to Linux 6.16 for gfx-ci
Signed-off-by: Ritesh Raj Sarraf <ritesh.sarraf@collabora.com>

ci: Downgrade to Linux 6.14 for venus-lavapipe jobs

In Linux 6.16 (and possibly 6.15 as well), the virtio gfx device
initialization seems to have regressed, resulting in device initialization
failure.

```
deqp-runner 0.20.3
+ deqp-runner suite --suite /builds/RickXy/mesa/install/deqp-venus.toml --output /builds/RickXy/mesa/results --skips /builds/RickXy/mesa/install/all-skips.txt /builds/RickXy/mesa/install/venus-skips.txt --flakes /builds/RickXy/mesa/install/venus-flakes.txt --testlog-to-xml /deqp-tools/testlog-to-xml --fraction-start 1 --fraction 60 --jobs 16 --baseline /builds/RickXy/mesa/install/venus-fails.txt
Error: Failed to invoke dEQP for dEQP-VK.info.device:
stdout:
Writing test log into /builds/RickXy/mesa/results/dEQP-VK.info.device
dEQP Core 3299a07b86cf0b15f86d1a441e323e515b15f255 (0x3299a07b) starting..
  target implementation = 'Default'
stderr:
MESA-VIRTIO: debug: one of required kernel params (4 or 9) is missing
FATAL ERROR: vk.enumeratePhysicalDevices(instance, &numDevices, nullptr): VK_ERROR_INITIALIZATION_FAILED at vkQueryUtil.cpp:83
```

Signed-off-by: Ritesh Raj Sarraf <ritesh.sarraf@collabora.com>

ci: Drop the test from the fail list

It is reported to pass with Linux 6.16

```
Unexpected results:
07:33:07.167:   KHR-GL46.sparse_texture2_tests.UncommittedRegionsAccess_texture_cube_map_r32i,Crash
07:33:07.167:   spec@!opengl 1.1@streaming-texture-leak,UnexpectedImprovement(Pass)
```

Signed-off-by: Ritesh Raj Sarraf <ritesh.sarraf@collabora.com>

ci: Update zink-avn-adl flakes list

Signed-off-by: Ritesh Raj Sarraf <ritesh.sarraf@collabora.com>

ci: Add flake to zink-anv-adl skip list

Signed-off-by: Ritesh Raj Sarraf <ritesh.sarraf@collabora.com>

ci: Add api@clgetdeviceinfo to Intel fails list

This api call is failing for Intel as well, like many of the other
types.

Signed-off-by: Ritesh Raj Sarraf <ritesh.sarraf@collabora.com>
Part-of: <https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/36493>