radv: Fix gnu-empty-initializer errors in cf29e98e
Fixes the following building errors:

../src/amd/vulkan/radv_pipeline.c:562:63: error: use of GNU empty initializer extension [-Werror,-Wgnu-empty-initializer]
   NIR_PASS(_, stage->nir, nir_opt_uub, &(nir_opt_uub_options){});
                                                              ^
1 error generated.

../src/amd/vulkan/radv_shader.c:204:80: error: use of GNU empty initializer extension [-Werror,-Wgnu-empty-initializer]
      NIR_LOOP_PASS(progress, skip, shader, nir_opt_uub, &(nir_opt_uub_options){});
                                                                               ^
1 error generated.

Fixes: cf29e98e ("radv: use nir_opt_uub")
Reviewed-by: Samuel Pitoiset <samuel.pitoiset@gmail.com>
Part-of: <https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/42367>