radv: Fix gnu-empty-initializer error in 6c3f80ff
Fixes the following building error:

../src/amd/vulkan/nir/radv_nir_lower_cooperative_matrix.c:499:39: error: use of GNU empty initializer extension [-Werror,-Wgnu-empty-initializer]
   struct nir_calc_tensor_info info = {};
                                      ^
1 error generated.

Fixes: 6c3f80ff ("radv: add support for coopmat2 tensorAddressing")
Reviewed-by: Georg Lehmann <dadschoorse@gmail.com>
Part-of: <https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/43207>