lavapipe: Fix gnu-empty-initializer error in 86305067
Fixes the following building error:

../src/gallium/frontends/lavapipe/nir/lvp_nir_lower_cooperative_matrix.c:696:39: error: use of GNU empty initializer extension [-Werror,-Wgnu-empty-initializer]
   struct nir_calc_tensor_info info = {};
                                      ^
1 error generated.

Fixes: 86305067 ("lavapipe: add tensorlayout and blockloads NV_cooperative_matrix2 support")
Part-of: <https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/43215>